#!/usr/bin/env bash

# This file implements a DSL to rebuild the history of this from Steven Eker's
# source commits. Using this DLS allows us to have a "second order" versioning
# over the history itself, and allows us to revert to previous histories
# if we mess up, as we poor humans do.
#
# As humans, we are vain too, and so go through the trouble to pretend that
# every commit we do is close to perfect. Thus we often go back and rewrite
# history. To allow doing this easily, we commit the patches themselves.
#
# Patches are generated using `git format-patch -1 <ref>`. 
# We don't try to use Eker's changes as patches since they'd be to unweildy to
# manage. 
#

set -e
base_dir="$(cd "$(dirname "$0")"; pwd)"

# DSL Implementation
# ==================

reset_worktree() {
    local worktree="$1"; shift
    cd "$base_dir"
    rm -rf "$worktree"
    git worktree prune
    git worktree add --detach "$worktree"
    cd "$worktree"
}

checkout() {
    local branch="$1"; shift
    local begin_ref="$1"; shift

    git checkout -b "$branch" "$begin_ref" 
}

apply_patch() {
    git am "$base_dir/patches/$1"
}

merge_range() {
    while read ref; do
        merge "$ref"
    done < <(git rev-list --reverse "$@")
}

merge() {
    local ref="$1"; shift
    git clean -dfx
    git merge --quiet --no-commit --strategy recursive --strategy-option ours "$ref" || true
    git ls-files --ignored --exclude-standard | sort -u | xargs -I file rm file
    git add -u

    local message="Import $(git log -1 --format=%s $ref)"
    git commit -m "$message"
}

# Description of history
# ======================

reset_worktree  build/worktree
checkout        "rebuild/1" 0d06e58f8e35
apply_patch     initial-gitignore.patch
apply_patch     initial-build.patch
apply_patch     initial-derive-from-eker.patch
merge_range     ^c8058de a1925ce 
apply_patch     full-maude27.patch
merge_range     ^a1925ce 3027849
