#!/usr/bin/env bash

set -e

stop_point="$1" && shift
eker_branch="origin/eker/develop"

current_eker() { git merge-base HEAD $eker_branch ; }
next_eker()    { git rev-list --topo-order "$(current_eker)..$eker_branch" | tail -n 1 ; }

do_next() {
    eker_next=$(next_eker)

    git clean -dfx

    git merge --no-commit --strategy recursive --strategy-option ours "$eker_next" || true

    git ls-files --ignored --exclude-standard | sort -u | xargs -I file rm file
    git add -u

    git commit --reuse-message="$eker_next" --no-edit

    git status
}

while [[ "$(current_eker)" != "$(git rev-parse "$stop_point")" ]]; do do_next; done
